### PR TITLE
Fixes to shared library build

### PR DESCRIPTION
**Pull request by troglobit**
In discussion #373 I mentioned the problems I saw trying to build .so files on Linux.  Turns out there were a couple of regressions introduced after #184 that broke it.

 1. The global cmake flag `BUILD_SHARED_DIRS` cannot be prefixed with `OPENER_`
 2. The linker order of libraries needed a slight change to work in both the static (default) and dynamic (.so) case

Included in this PR are three patches that address these two issues.  First fix the linker ordering issue.  Next rename the cmake variable back to its original, to get shared libraries built.  Lastly, the install stage is separated from the shared library setting to allow installing as static library as well (default if install is selected).  I've taken the liberty of updating the README.md and the top-level source CMakeLists.txt according to the [recommendation in the cmake manual](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html).

### CODE REVIEW

**Comment by troglobit** [comment]
I don't understand why the GCC build fails on Travis, the actual build seems to go fine.  Maybe it's some repo permission thing with SonarCloud?

The error is:
```
ERROR: Error during SonarScanner execution
ERROR: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator
ERROR: 
ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.

The command "$TRAVIS_BUILD_DIR/travis_scripts/linuxScript.sh" exited with 2.
```

**Comment by troglobit** [comment]
Sorry about the force-push, just realized my last patch was polluted with another change.  The force-push clears this up and I don't expect any more changes to this PR unless requested by a reviewer.

**Comment by CapXilinx** [comment]
Many thanks @troglobit

**Comment by CapXilinx** [comment]
Regarding Travis,

yes that's a privileges/application token issue. I patched that together, so that I get a SonarCloud analysis for OpENer.
Never figured out how to make this work for forks, but I will take a look on it.

**Pull request merged**
