### PR TITLE
Warnings

### PR DESCRIPTION
**Pull request by jvalenzuela**
Updated pull request to master, a066b34, addressing VS and some GCC compiler warnings.

### CODE REVIEW

**Comment by widavies** [comment]
Could we get this merged?

**Comment by jvalenzuela** [comment]
I realize this is a lot of changes. I can help make it easier to merge, perhaps selecting one commit at a time to consider, then reorder or rebase it as necessary to make it a simple, FF merge into master, resulting in a linear history.

**Comment by widavies** [comment]
I'd be willing to help review & test this if needed as well to get it merged.

**Comment by CapXilinx** [comment]
Hi, also here sorry for the very long delay.
Yes, if we could split this in several PRs this would be easier. I already know I can not merge all, as at least one of your cleanups would again open a security leak, enabling to put OpENer into an infinite loop

**Comment by jvalenzuela** [comment]
Ok, I'll close this pull request, rebase as needed, and open new pull requests for each.

**Pull request closed without merging**
